title: "DT Vega Architecture Chapter"
description: "Yazılım mimarileri, DevOps, oyun programlama, yapay zeka ve sistem tasarımı alanlarında açık kaynak örnek projeler."
lang: tr-TR
url: https://dtvegaarchchapter.github.io
baseurl: ""
# Jekyll GitHub Pages theme
theme: jekyll-theme-slate
# Site settings
show_downloads: false
github_username: DTVegaArchChapter
# Build settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO / sosyal
author: "DT Vega Architecture Chapter"
logo: /assets/img/logo.png
social:
  name: DT Vega Architecture Chapter
  links:
    - https://github.com/DTVegaArchChapter

# Koleksiyonlar ileride eklenebilir
collections: {}

# Navigasyon (elle kullanılacak)
nav:
  - title: Ana Sayfa
    url: /
  - title: Projeler
    url: /projeler
  - title: Blog
    url: /blog
  - title: Hakkımızda
    url: /hakkimizda
  - title: Katkıda Bulun
    url: /katki

# Proje verileri (include ile kullanılır)
projects:
  - name: Architecture
    repo: Architecture
    url: https://github.com/DTVegaArchChapter/Architecture
    description: Mikroservis, DDD, Event-Driven, entegrasyon ve pattern örnekleri.
    tags: [microservices, ddd, architecture]
    featured: true
    order: 1
  - name: DevOps
    repo: DevOps
    url: https://github.com/DTVegaArchChapter/DevOps
    description: Monitoring, logging, alerting, gözlemlenebilirlik demo kurulumları.
    tags: [devops, observability]
    featured: true
    order: 2
  - name: GameProgramming
    repo: GameProgramming
    url: https://github.com/DTVegaArchChapter/GameProgramming
    description: Go & Rust ile oyun geliştirme deneysel mini projeleri.
    tags: [game, go, rust]
    featured: true
    order: 3
  - name: AI
    repo: AI
    url: https://github.com/DTVegaArchChapter/AI
    description: Yapay zeka konularını öğrenmek için örnekler, modeller ve rehberler.
    tags: [ai, ml, experiments]
    featured: false
    order: 4
  - name: SystemDesign
    repo: SystemDesign
    url: https://github.com/DTVegaArchChapter/SystemDesign
    description: Ölçeklenebilir sistem tasarımı, kapasite ve performans senaryoları.
    tags: [system-design, scalability, performance]
    featured: false
    order: 5
  - name: CoinBazaar
    repo: CoinBazaar
    url: https://github.com/DTVegaArchChapter/CoinBazaar
    description: Popüler pattern ve framework entegrasyonlarını birleştiren örnek platform.
    tags: [architecture, patterns, integration]
    featured: false
    order: 6
  - name: SoftwareArchitectLearningPath
    repo: SoftwareArchitectLearningPath
    url: https://github.com/DTVegaArchChapter/SoftwareArchitectLearningPath
    description: Yazılım Mimarı öğrenim yolu dokümanı.
    tags: [learning, architecture, roadmap]
    featured: false
    order: 7
  - name: PersonnelMongoDb
    repo: PersonnelMongoDb
    url: https://github.com/DTVegaArchChapter/PersonnelMongoDb
    description: MongoDB ile personel yönetimi CRUD örneği.
    tags: [mongodb, crud, csharp]
    featured: false
    order: 8
  - name: LongRunningExternalRequestMessaging
    repo: LongRunningExternalRequestMessaging
    url: https://github.com/DTVegaArchChapter/LongRunningExternalRequestMessaging
    description: Uzun süren HTTP isteklerini asenkronlaştıran messaging tabanlı tasarım.
    tags: [system-design, messaging, resiliency]
    featured: false
    order: 9

excerpt_separator: "<!--more-->"
